# Generated by Django 3.1.7 on 2021-02-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mst_PPI100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Code', models.IntegerField()),
                ('Commodity', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
