# Generated by Django 3.1.7 on 2021-02-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPI100', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mst_PPI100',
        ),
    ]
