# Generated by Django 3.1.7 on 2021-03-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPI100', '0003_mst_ppi100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mst_PPI100',
        ),
    ]
