# Generated by Django 3.0.7 on 2021-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mst_sunsris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Code', models.IntegerField()),
                ('Commodity', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
